//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoveItDemo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataHandlerEntities : DbContext
    {
        public DataHandlerEntities()
            : base("name=DataHandlerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<PriceOffert> PriceOfferts { get; set; }

        public System.Data.Entity.DbSet<MoveItDemo.Models.ViewModels.PriceSuggestion> PriceSuggestions { get; set; }

        public System.Data.Entity.DbSet<MoveItDemo.Models.ViewModels.PriceOffers> PriceOffers { get; set; }
    }
}
