//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoveItDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceOffert
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string FromName { get; set; }
        public string ToName { get; set; }
        public string Distance { get; set; }
        public Nullable<int> ResidenceArea { get; set; }
        public Nullable<int> WindBaseMentArea { get; set; }
        public Nullable<bool> PianoStatus { get; set; }
        public Nullable<bool> PackingStatus { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
